[log]
level = "INFO"
# [ping]

[providers.docker]
exposedbydefault = false
[providers.file]
directory="/etc/traefik/additional/" 
watch=true 

[entrypoints.http]
address = ":80"
[entrypoints.https]
address = ":443"
[entrypoints.https.http3]

[entrypoints.matrix]
address = ":8448"
[entrypoints.matrix.http3]

[entryPoints.http.proxyProtocol]
insecure = false
trustedIPs = [ ]

[entryPoints.http.forwardedHeaders]
insecure = false
trustedIPs = [ ]

[entryPoints.https.proxyProtocol]
insecure = false
trustedIPs = [ ]

[entryPoints.https.forwardedHeaders]
insecure = false
trustedIPs = [ ]

[entryPoints.matrix.proxyProtocol]
insecure = false
trustedIPs = [ ]

[entryPoints.matrix.forwardedHeaders]
insecure = false
trustedIPs = [ ]

[entrypoints.http.http.redirections.entryPoint]
to="https" 
scheme = "https"

[http.middlewares]
[http.middlewares.traefik-compress.compress]

[http.routers.http]
middlewares = "traefik-compress"
[http.routers.https]
middlewares = "traefik-compress"
[http.routers.traefik]
middlewares = "traefik-compress"
# [entryPoints.traefik]
# address = ":9000"


[certificatesresolvers.letsencrypt.acme]
email = 'jade@ellis.link'
storage = "/certificates/acme.json"

# - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
# - "--certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint=http"
tlschallenge = true
