[package]
name = "conduwuit_web"
description.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "mod.rs"
crate-type = [
	"rlib",
#	"dylib",
]

[features]


[dependencies]
conduwuit-build-metadata.workspace = true
conduwuit-service.workspace = true
askama.workspace = true
axum.workspace = true
futures.workspace = true
tracing.workspace = true
rand.workspace = true
snafu.workspace = true

[lints]
workspace = true
