# Please see the relevant documentation.
# Performance tuning: https://docs.sentry.io/product/relay/operating-guidelines/
# All config options: https://docs.sentry.io/product/relay/options/
relay:
  mode: static
  upstream: https://o4507835405369344.ingest.de.sentry.io/
  host: 0.0.0.0
  port: 3000

